var
  _ = require('lodash');

var AdWordsReport = require('./adWordsReport');

function Report(options) {
  var self = this;
  self.defaultFieldNames = [
    'UrlCustomParameters',
    // 'ViewThroughConversionsSignificance',
    'AccountCurrencyCode',
    'AccountDescriptiveName',
    'AccountTimeZoneId',
    // 'ActiveViewCpm',
    // 'ActiveViewCtr',
    // 'ActiveViewImpressions',
    // 'ActiveViewMeasurability',
    // 'ActiveViewMeasurableCost',
    // 'ActiveViewMeasurableImpressions',
    // 'ActiveViewViewability',
    'AdGroupId',
    'AdGroupName',
    'AdGroupStatus',
    'AdNetworkType1',
    'AdNetworkType2',
    // 'AdvertiserExperimentSegmentationBin',
    // 'AllConversionRate',
    // 'AllConversions',
    // 'AllConversionValue',
    // 'AverageCost',
    // 'AverageCpc',
    // 'AverageCpe',
    // 'AverageCpm',
    // 'AverageCpv',
    // 'AveragePageviews',
    // 'AveragePosition',
    // 'AverageTimeOnSite',
    // 'AvgCostForOfflineInteraction',
    'BiddingStrategyId',
    'BiddingStrategyName',
    'BiddingStrategyType',
    'BidType',
    // 'BounceRate',
    'CampaignId',
    'CampaignName',
    'CampaignStatus',
    // 'ClickAssistedConversions',
    // 'ClickAssistedConversionsOverLastClickConversions',
    // 'ClickAssistedConversionValue',
    'ClickConversionRate',
    // 'ClickConversionRateSignificance',
    // 'Clicks',
    // 'ClickSignificance',
    // 'ClickType',
    'ContentBidCriterionTypeGroup',
    // 'ContentImpressionShare',
    // 'ContentRankLostImpressionShare',
    // 'ConversionCategoryName',
    'ConversionRate',
    'Conversions',
    // 'ConversionTrackerId',
    // 'ConversionTypeName',
    'ConversionValue',
    'ConvertedClicks',
    // 'ConvertedClicksSignificance',
    'Cost',
    // 'CostPerAllConversion',
    'CostPerConversion',
    'CostPerConvertedClick',
    // 'CostPerConvertedClickSignificance',
    // 'CostSignificance',
    'CpcBid',
    // 'CpcSignificance',
    'CpmBid',
    // 'CpmSignificance',
    'CpvBid',
    // 'CrossDeviceConversions',
    'Ctr',
    // 'CtrSignificance',
    'CustomerDescriptiveName',
    'Date',
    'DayOfWeek',
    // 'Device',
    'EngagementRate',
    'Engagements',
    'EnhancedCpcEnabled',
    'EnhancedCpvEnabled',
    'ExternalCustomerId',
    'GmailForwards',
    'GmailSaves',
    'GmailSecondaryClicks',
    // 'HourOfDay',
    // 'ImpressionAssistedConversions',
    // 'ImpressionAssistedConversionsOverLastClickConversions',
    // 'ImpressionAssistedConversionValue',
    'Impressions',
    // 'ImpressionSignificance',
    'InteractionRate',
    'Interactions',
    'LabelIds',
    'Labels',
    'Month',
    'MonthOfYear',
    // 'NumOfflineImpressions',
    // 'NumOfflineInteractions',
    // 'OfflineInteractionCost',
    // 'OfflineInteractionRate',
    // 'PercentNewVisitors',
    // 'PositionSignificance',
    'PrimaryCompanyName',
    'Quarter',
    // 'RelativeCtr',
    // 'SearchExactMatchImpressionShare',
    // 'SearchImpressionShare',
    // 'SearchRankLostImpressionShare',
    // 'Slot',
    'TargetCpa',
    'TotalCost',
    'TrackingUrlTemplate',
    'ValuePerAllConversion',
    'ValuePerConversion',
    'ValuePerConvertedClick',
    'VideoQuartile100Rate',
    'VideoQuartile25Rate',
    'VideoQuartile50Rate',
    'VideoQuartile75Rate',
    'VideoViewRate',
    'VideoViews',
    'ViewThroughConversions',
    'Week',
    'Year'
  ];

  self.reportName = 'Ad Group Performance Report';
  self.reportType = 'ADGROUP_PERFORMANCE_REPORT';
  AdWordsReport.call(self, options);
}

Report.prototype = _.create(AdWordsReport.prototype, {
  'constructor': Report
});

module.exports = (Report);
